//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipdBody
    {
        public string HN { get; set; }
        public string RegNo { get; set; }
        public string AN { get; set; }
        public int Seq { get; set; }
        public string wk_Period { get; set; }
        public System.DateTime wk_date { get; set; }
        public string wk_date_text { get; set; }
        public System.TimeSpan wk_time { get; set; }
        public string wk_time_text { get; set; }
        public decimal Weight { get; set; }
        public decimal Height { get; set; }
        public decimal Waistline { get; set; }
        public decimal Hip { get; set; }
        public decimal BM1 { get; set; }
        public decimal Head { get; set; }
        public decimal Chest { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    }
}
