//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ipdVitalSign
    {
        public string HN { get; set; }
        public string RegNo { get; set; }
        public string AN { get; set; }
        public int Seq { get; set; }
        public string wk_Period { get; set; }
        public System.DateTime wk_date { get; set; }
        public string wk_date_text { get; set; }
        public System.TimeSpan wk_time { get; set; }
        public string wk_time_text { get; set; }
        public decimal Systolic { get; set; }
        public decimal Diastotic { get; set; }
        public decimal MAP { get; set; }
        public decimal O2Sat { get; set; }
        public decimal O2SatPreduct { get; set; }
        public decimal O2SatPostduct { get; set; }
        public decimal Plus { get; set; }
        public decimal Respirations { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public System.DateTime CreateOn { get; set; }
    }
}
