//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HosSystemEntities : DbContext
    {
        public HosSystemEntities()
            : base("name=HosSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ipdEmployee> ipdEmployees { get; set; }
        public virtual DbSet<ipdBody> ipdBodies { get; set; }
        public virtual DbSet<ipdTemperature> ipdTemperatures { get; set; }
        public virtual DbSet<ipdVitalSign> ipdVitalSigns { get; set; }
        public virtual DbSet<ipdPain> ipdPains { get; set; }
        public virtual DbSet<ipdFluid> ipdFluids { get; set; }
        public virtual DbSet<ipdOther> ipdOthers { get; set; }
    }
}
