//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HosSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ptl_consult
    {
        public string cs_id { get; set; }
        public string AN { get; set; }
        public string cs_date { get; set; }
        public Nullable<System.DateTime> cs_time { get; set; }
        public string cs_cname { get; set; }
        public string cs_header { get; set; }
        public string cs_detail { get; set; }
        public string cs_status { get; set; }
        public string acc_doc { get; set; }
        public string doc_comment { get; set; }
        public string acc_date { get; set; }
        public Nullable<System.DateTime> acc_time { get; set; }
        public string order_id { get; set; }
    }
}
